version: "3.8"
services:
  elastic:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
      container_name: elastic
      environment:
        - node.name=elastic
        - cluster.name=es-docker-cluster
        - discovery.type=single-node
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - ELASTIC_PASSWORD="${ELASCTIC_PASSWORD}"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - data01:/usr/share/elasticsearch/data
      ports:
        - 9200:9200
volumes:
  data01:
    driver: local